rules:
  # geoblocked domains
  - domains: lists/geoblocked.txt
    outbound: vpn
  # google deepmind domains
  - domains: lists/google-deepmind.txt
    outbound: vpn
  # discord subnets
  - subnets: lists/discord.txt
    outbound: warp
  # discord domains
  - domains: lists/discord-domains.txt
    outbound: warp
  # whatsapp subnets
  - subnets: https://raw.githubusercontent.com/HybridNetworks/whatsapp-cidr/main/WhatsApp/whatsapp_cidr_ipv4.txt
    outbound: warp
